services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./volumes:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "question_scraper"]
